### ISSUE TITLE
Get-QVAssignedUsers error

### ISSUE THREAD

**Issue by chevcheli0s** [QlikProfessionalServices/QlikView-CLI#1]
**Describe the bug**
When try to call Get-QVAssignedUsers I recive an error:
```
Get-QVAssignedUsers : An error occurred while receiving the HTTP response to http://myserver.domain:4799/QMS/Service. This could be due to the service endpoint binding not using the 
HTTP protocol. This could also be due to an HTTP request context being aborted by the server (possibly due to the service shutting down). See server logs for more details.
At line:3 char:1
 Get-QVAssignedUsers
     CategoryInfo          : NotSpecified: (QlikView_CLI.QMSAPI.QMS5Client:QMS5Client) [Get-QVAssignedUsers], CommunicationException
     FullyQualifiedErrorId : mscorlib,QlikView_CLI.PWSH.GetQVAssignedUsers
```
I am using this script:
```
$myFQDN=(Get-WmiObject win32_computersystem).DNSHostName+"."+(Get-WmiObject win32_computersystem).Domain
$myFQDN = $myFQDN.ToLower()
Connect-QlikView -Hostname $($myFQDN) -Version IQMS5
Get-QVCALConfiguration -qvsID (Get-QVServices -Servicetypes QlikViewServer).ID -Scope All
Get-QVAssignedUsers
```

**To Reproduce**
1. Call Get-QVAssignedUsers
2. See error

**Expected behavior**
Get users

**Screenshots**
![image](https://user-images.githubusercontent.com/48658076/155161595-9a2d0d32-0057-4f4a-b722-3030bd72f7da.png)

**Environment (please complete the following information):**
 - QlikView Version: April 2020 SR4
 - PowerShell Version: 5.1.14393.4530 
 - OS:  Server 2016
 - Version 1.6.21167.16064

**Comment by Nillth** [comment]
Hi @chevcheli0s,
The Error you are getting occurs when your environment is licensed using a LEF based License.

![image](https://user-images.githubusercontent.com/22066262/155253288-9575bac6-b46c-468e-9900-062e33ea11f4.png)

if you use a SLK License it should work as expected. 
![image](https://user-images.githubusercontent.com/22066262/155254010-a86af52c-0e82-4da3-9c39-fd6689d74df4.png)

The Function you are using `Get-QVAssignedUsers` uses the underlying method [IQMS5.GetAssignedUsers](https://help.qlik.com/en-US/qlikview-developer/May2021/Subsystems/QMSAPIref/Content/PIX.Services.V12.Api5.IQMS5.GetAssignedUsers.htm) which is not very well documented in the QMSAPI Reference sites.
The method [IQMS5.GetAssignedUsers](https://help.qlik.com/en-US/qlikview-developer/May2021/Subsystems/QMSAPIref/Content/PIX.Services.V12.Api5.IQMS5.GetAssignedUsers.htm)  was introduced with the SLK License type and when it is used in an environment with a SLK it correctly returns the users Assigned licenses from the SLK.


Based on the context the script you provided, I suspect that you are trying to see what users have licenses assigned within the platform.

The objects returned from the Functions have a lot of data in them that you can explore if you capture them in variables.
For example, if we capture the output of the Connect-QlikVIew funciton
We can then reference the properties to see more details about each of the objects. 
![image](https://user-images.githubusercontent.com/22066262/155256330-08058ae6-8c50-4bc4-9e95-f8846a19fa6e.png)

We can also use that information later in the script, e.g. when we need to reference the qvsID
![image](https://user-images.githubusercontent.com/22066262/155256669-36628ae2-1d68-4a40-900b-e2930ff1e361.png)

And finally once we have something like the CalConfiguration we can dig down on each of the properties to see all the data.
![image](https://user-images.githubusercontent.com/22066262/155256889-3983e88a-4854-4276-bec9-117e817aded4.png)

Also the hostname paramater on Connect-QlikView should only be required if you have nonstandard configuration or are running from a remote server.

```PowerShell
$QVConnection = Connect-QlikView -Version IQMS5
$QVConnection
$QVConnection.QlikViewServer
$QVCALConfiguration = Get-QVCALConfiguration -Scope All -qvsID $QVConnection.QlikViewServer[0].ID
$QVCALConfiguration
$QVCALConfiguration.NamedCALs
$QVCALConfiguration.NamedCALs.AssignedCALs
```
