### ISSUE TITLE
IQMS7

### ISSUE THREAD

**Issue by chevcheli0s** [QlikProfessionalServices/QlikView-CLI#2]
**Describe the bug**
There is no parameter IQMS7 in https://github.com/QlikProfessionalServices/QlikView-CLI/blob/main/PWSH/ConnectQlikView.cs 
The last version is IQMS6 that able to use in Connect-QlikView -Version

**Comment by Nillth** [comment]
Sorry, I noticed that post release
I have had the fix sitting in my local repo. 2057460415123d676d16ffe71e6994bfc012d198 
Republished to [PSGallery](https://powershellgallery.com/packages/QlikView-CLI/1.7.22199)
And I have updated the [release](https://github.com/QlikProfessionalServices/QlikView-CLI/releases/tag/1.7.22159.3424) with the corrected build
