### ISSUE TITLE
Get-QVTaskStatuses returns nothing

### ISSUE THREAD

**Issue by chevcheli0s** [QlikProfessionalServices/QlikView-CLI#3]
**Describe the bug**
Get-QVTaskStatuses returns nothing

**To Reproduce**
Get-QVTaskStatuses -Filter (New-QVTaskStatusFilter -Enabledstate Any)

**Expected behavior**
Return list of tasks statuses 

**Environment (please complete the following information):**
 - QlikView Version: 12.70
 - PowerShell Version: 5.1.14393.4583
 - OS: Server 2019

**Comment by chevcheli0s** [comment]
Script from [this](https://community.qlik.com/t5/QlikView-Administration/Call-QMS-API-with-PowerShell-and-get-running-tasks/td-p/1560940) thread returns tasks

**Comment by Nillth** [comment]
`New-QVTaskStatusFilter` populates a default value to `LastExecution` & `Schedule`
you can see this by running `New-QVTaskStatusFilter` or `New-QVTaskStatusFilter|Convertto-json`

if you adjust your call to the following it should work
```PowerShell
Get-QVTaskStatuses -Scope All -Filter $(New-QVTaskStatusFilter -Enabledstate Any -Lastexecution $Null -Schedule $Null)
```

**Comment by chevcheli0s** [comment]
Thanks!
